### ISSUE TITLE
Microsoft.Practices.ServiceLocation 

### ISSUE THREAD

**Issue by a3code** [mausch/SolrNet#210]
I am trying to run some basic stuff 

``` c#
Solr.Connection = new SolrConnection("http://localhost:8282/solr/sitecore_master_index");
            //Startup.Init<Course>("http://localhost:8282/solr/sitecore_master_index");
            var r = Solr.Query<Course>().By("university_t").Is("uk").Run();
            //var solr = ServiceLocator.Current.GetInstance<ISolrOperations<Course>>();
            //var results = solr.Query(new SolrQueryByField("university_t", "uk"));
            Assert.IsTrue(r != null);
```

But I am getting error all the time Microsoft.Practices.ServiceLocation presents in my assembly references  

*An exception of type 'System.IO.FileLoadException' occurred in SolrNet.dll but was not handled in user code

Additional information: Could not load file or assembly 'Microsoft.Practices.ServiceLocation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)*

**Comment by mausch** [comment]
Hi there. As mentioned [in the docs](https://github.com/mausch/SolrNet/blob/master/Documentation/Fluent-API.md#querying) that style of querying is deprecated. See https://github.com/mausch/SolrNet/blob/master/Documentation/Querying.md instead.

About the missing Microsoft.Practices.ServiceLocation.dll, the [SolrNet nuget package](https://www.nuget.org/packages/SolrNet) does reference it as a dependency. Try removing the package and adding it back again.

**Comment by a3code** [comment]
I done that you wrote about reinstall package and was't added Microsoft.Practices.ServiceLocation.dll
and I get new error 
*Could not load type 'SolrNet.ISolrCoreAdmin' from assembly 'SolrNet, Version=0.4.0.4001, Culture=neutral, PublicKeyToken=null'.*

**Comment by xaviermorera** [comment]
@a3code as a first step have you tried download the project from Github and compiling? I recommend you do this as a first step when getting started as it helps learning a bit about SolrNet. Why don't you give it a shot?

If the answer is no, I had a similar experience similar to this one on ServiceLocation and it was because another dependency was using a newer version so I had to add an assemblyredirect. I solved it by using FusLogViewer to find out which library had the dependency.

**Comment by HarshCLAD** [comment]
@xmorera Hi , Xavier I am very new to this technology and want to get facets for which i had seen your code but i cannot understand what are the three dots that was used in your code and since they are giving compile time error for the code -        

ISolrOperations<Document> solr = ...

Please help me find the solution because I am unable to resolve it and understand it . Thanks in Advance
