### ISSUE TITLE
DataImportHandle Implementation in SolrNet 5.0

### ISSUE THREAD

**Issue by himanshu0a** [mausch/SolrNet#228]
Hi,

We are using Solr version 5.4.1 and SolrNet version 5.0 and we are stuck in an issue.

We want to use the schemaless approach for our project.
Earlier we used put our query in the data-config file and call the appropriate handle but now we are trying to configure it using the SolrNet and this is where we are stuck. 
Can you please provide the solution as if how can we configure this data-config file so that we can add a new field to this query using the SolrNet which we are adding to our schema.

Note : We are fetching the data using the sql server.

**Comment by mausch** [comment]
Just to be sure I understand, you're trying to move away from DataImportHandler into an implementation that loads data into Solr using a process written with SolrNet?
If the problem is with schemaless, have you seen https://github.com/mausch/SolrNet/blob/master/Documentation/Mapping.md#fully-loose-mapping ?

**Comment by himanshu0a** [comment]
Yes I got this one around and it helped Thanks.
